# -*- coding: utf-8 -*-
"""test_loader.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P7u2ngX2zW_4pGahOodTzbZOZWYhFnNc
"""

# test/test_loader.py
from src.data.loader import load_data

def test_load_data():
  df = load_data("data/train.csv")
  assert df.shape[0] > 0
  assert "Survived" in df.columns