# -*- coding: utf-8 -*-
"""base_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P7u2ngX2zW_4pGahOodTzbZOZWYhFnNc
"""

# src/models/base_model.py
from abc import ABC, abstractmethod

class BaseModel(ABC):
    def __init__(self, model_name):
        self.model_name = model_name
        self.model = None

    @abstractmethod
    def train(self, X_train, y_train):
      self.model.fit(X_train, y_train)

    @abstractmethod
    def predict(self, X_test):
        return self.model.predict(X_test)

    def evaluate(self, X_test, y_test, evaluator):
        y_pred = self.predict(X_test)
        return evaluator.evaluate(y_test, y_pred)

    def predict_proba(self, X_test):
        if hasattr(self.model, 'predict_proba'):
            return self.model.predict_proba(X_test)
        else:
            raise ValueError("Model does not support predict_proba method.")