# -*- coding: utf-8 -*-
"""xgboost_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P7u2ngX2zW_4pGahOodTzbZOZWYhFnNc
"""

# src/models/xgboost_model.py
from xgboost import XGBClassifier
from .base_model import BaseModel

class XGBoost(BaseModel):
  def __init__(self, n_estimators=100, max_depth=3, learning_rate=0.1, random_state=42):
    super().__init__("XGBoost")
    self.model = XGBClassifier(**(params or {}))

# test/test_loader.py
from src.data.loader import load_data

def test_load_data():
  df = load_data("data/train.csv")
  assert df.shape[0] > 0
  assert "Survived" in df.columns